---
apiVersion: v1
kind: Service
metadata:
  name: vaultsecretidfactory
spec:
  selector:
    app: vaultsecretidfactory
  ports:
  - port: 8314
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: vaultsecretidfactory
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: vaultsecretidfactory
    spec:
      serviceAccountName: vault-auth
      containers:
      - name: vaultsecretidfactory
        image: allthingscloud/vaultsecretidfactory
        ports:
        - name: http-api
          containerPort: 8314
